services:
  - type: web
    name: forest-fire-node-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URL
        sync: false
      - key: TOKEN_KEY
        sync: false
      - key: EMAIL
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: MAILBOXLAYER_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

  - type: web
    name: forest-fire-flask-api
    env: python
    plan: free
    rootDir: server/model
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENWEATHER_KEY
        sync: false
      - key: AGRO_POLY_ID
        sync: false
      - key: GEE_SERVICE_ACCOUNT
        sync: false
      - key: GEE_PROJECT_ID
        sync: false
      - key: GEE_PRIVATE_KEY_ID
        sync: false
      - key: GEE_CLIENT_ID
        sync: false
      - key: GEE_CLIENT_EMAIL
        sync: false
      - key: GEE_PRIVATE_KEY
        sync: false
      - key: LANDCOVER_DOWNLOAD_URL
        sync: false
